[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.15.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
